apiVersion: apps/v1
kind: Deployment
metadata:
  name: actors-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actors-host
  template:
    metadata:
      labels:
        app: actors-host
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "actors"
        dapr.io/app-port: "5050"
    spec:
      containers:
        - name: actors-host
          image: {{ .Values.PrivateContainerRegistry }}{{ .Release.Name }}-actors-host:latest
          ports:
            - containerPort: 5050