apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: broadcast
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: consumerID
      value: "{uuid}"
      